FROM ianmgg/php74:dev

COPY ./scripts/docker/config/apache/mpm_prefork.conf /etc/apache2/mods-enabled/mpm_prefork.conf
COPY ./scripts/docker/config/apache/status.conf /etc/apache2/mods-enabled/status.conf
COPY ./scripts/docker/config/php/startup-queue.sh /usr/local/bin/startup
COPY ./scripts/docker/config/apache/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./scripts/docker/config/php/sessions.ini /usr/local/etc/php/conf.d/sessions.ini

WORKDIR /var/www

RUN rm -rf /var/www/html
COPY . /var/www/
RUN composer install \
  && chmod -R g+w /var/www \
  && chmod 755 /usr/local/bin/startup

ENV MYSQL_DATABASE "flarum"
ENV MYSQL_USER "flarum"
ENV MYSQL_PASSWORD "flarum"
ENV MYSQL_HOST "communitydb"
ENV MYSQL_PORT "3306"

CMD ["startup"]
